baseURL = "https://madneal.com"
#baseURL = "https://cdn.jsdelivr.net/gh/neal1991/neal1991.github.io"
languageCode = "en"
title = "Neal's Blog"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "nealecnu"

# Google Analytics UA number
googleAnalytics = "UA-104405154-2"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Works"
  weight = 20
  identifier = "works"
  url = "https://github.com/madneal"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Neal"
  avatar = "https://cdn.jsdelivr.net/gh/neal1991/neal1991.github.io/img/avatar.jpg"
  wechat = "https://cdn.jsdelivr.net/gh/neal1991/neal1991.github.io/img/wechat.jpg"
  seotitle = "Neal 的博客"
  subtitle = "Development & Security"
  description = "全栈工程师的进击"
  paginate = 10

  # Choose your social networks
  email = "bing.ecnu@gmail.com"
  github = "madneal"

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  #msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"
